# Generated by Django 5.0.1 on 2024-01-14 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_department_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18555cef-1cc3-5eea-81da-7eabeed251ec'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18555cef-1cc3-5eea-81da-7eabeed251ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
