# Generated by Django 5.0.1 on 2024-01-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_department_id_alter_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
    ]
