# Generated by Django 5.0.1 on 2024-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_department_employee_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
